language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
  - lts/*
  - 8
install:
  - npm ci
  - npm i --no-save puppeteer-firefox
after_success:
  - npx codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
